import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// components
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-1 flex justify-center">
          <div className="flex flex-col bg-black rounded-xl min-h-[98vh] w-[98vw]">
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
